name: 🚀 Deploy ke InfinityFree (accr.ct.ws)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  ftp-deploy:
    name: Upload via FTP ke htdocs
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout kode
        uses: actions/checkout@v4

      - name: 📂 Sync file ke htdocs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.github/**/*
            README.md
